import { useState, useEffect, useRef } from "react";
import { useGetIdentity, useNotify } from "ra-core";
import { supabase } from "@/components/atomic-crm/providers/supabase/supabase";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import { Loader2, Zap, ZapOff } from "lucide-react";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

export const ProcessingStatusIndicator = () => {
  const [enabled, setEnabled] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);
  const [processedCount, setProcessedCount] = useState(0);
  const { identity } = useGetIdentity();
  const notify = useNotify();
  const processingRef = useRef(false);

  // Poll for work
  useEffect(() => {
    let intervalId: NodeJS.Timeout;

    const checkForWork = async () => {
      // Prevent overlapping runs
      if (!enabled || processingRef.current || !identity?.id) return;

      try {
        // 1. Claim Work
        // We need the Sales ID, not just Auth ID. 
        // Assuming identity.id corresponds to user_id in sales table, we need to lookup sales_id first?
        // Actually, the RPC takes `p_agent_sales_id`. 
        // We can fetch the sales record for the current user.
        
        const { data: salesData, error: salesError } = await supabase
            .from("sales")
            .select("id")
            .eq("user_id", identity.id)
            .single();
            
        if (salesError || !salesData) return;

        const { data, error } = await supabase.rpc(
          "claim_next_pending_activity",
          { p_agent_sales_id: salesData.id }
        );

        if (error) {
          console.error("Error claiming work:", error);
          return;
        }

        // If we got work (RPC returns an array of rows)
        if (data && data.length > 0) {
          const task = data[0];
          processingRef.current = true;
          setIsProcessing(true);

          console.log("Processing task:", task);

          // 2. Simulate AI Processing (The "Local Processor")
          // In a real app, this is where we'd run the ASR/LLM models
          await new Promise((resolve) => setTimeout(resolve, 3000));

          // 3. Complete the Task
          const { error: updateError } = await supabase
            .from("activities")
            .update({
              processing_status: "completed",
              processed_data: {
                summary: "Automatically processed by Local Agent.",
                transcript: "This is a simulated transcript generated by the local node.",
                atomic_facts: ["Fact 1", "Fact 2"]
              }
            })
            .eq("id", task.id);

          if (updateError) {
             console.error("Failed to update task:", updateError);
             notify("Failed to save processed task", { type: "error" });
          } else {
             setProcessedCount((prev) => prev + 1);
             notify("Activity processed locally", { type: "info", undoable: false });
          }

          processingRef.current = false;
          setIsProcessing(false);
        }
      } catch (err) {
        console.error("Processing loop error:", err);
        processingRef.current = false;
        setIsProcessing(false);
      }
    };

    if (enabled) {
      intervalId = setInterval(checkForWork, 5000); // Poll every 5 seconds
      checkForWork(); // Run immediately
    }

    return () => clearInterval(intervalId);
  }, [enabled, identity, notify]);

  if (!identity) return null;

  return (
    <div className="flex items-center gap-3 px-3 py-1.5 bg-background border rounded-full shadow-sm ml-4">
      <TooltipProvider>
        <Tooltip>
          <TooltipTrigger asChild>
            <div className="flex items-center gap-2">
              <Switch
                checked={enabled}
                onCheckedChange={setEnabled}
                className="scale-75"
              />
              {enabled ? (
                isProcessing ? (
                  <div className="flex items-center gap-2 text-primary animate-pulse">
                    <Loader2 className="h-4 w-4 animate-spin" />
                    <span className="text-xs font-medium">Processing...</span>
                  </div>
                ) : (
                  <div className="flex items-center gap-2 text-muted-foreground">
                    <Zap className="h-4 w-4 fill-yellow-400 text-yellow-400" />
                    <span className="text-xs font-medium">Ready</span>
                  </div>
                )
              ) : (
                <div className="flex items-center gap-2 text-muted-foreground">
                    <ZapOff className="h-4 w-4" />
                    <span className="text-xs">Node Off</span>
                </div>
              )}
            </div>
          </TooltipTrigger>
          <TooltipContent>
            <p>Turn on to use this device as a Local Processing Node for CRM activities.</p>
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>

      {processedCount > 0 && (
        <Badge variant="secondary" className="text-[10px] h-5 px-1.5">
          {processedCount}
        </Badge>
      )}
    </div>
  );
};
